### ISSUE TITLE
Can't confine open-vm-tools with AppArmor

### ISSUE THREAD

**Issue by goldstar611** [bzed/pkg-open-vm-tools#17]
Hi, I'm trying to confine various popular root processes and this one is tricky.

I originally opened an issue on the [AppArmor Gitlab](https://gitlab.com/apparmor/apparmor/issues/13) project and proposed a workaround that involves modifying the ```open-vm-tools.service``` file (which they later improved the suggesting by adding
```After=apparmor.service```

I've tested this modification in VMWare Workstation 15 (Linux host + Linux Guest) and it seems to be working as expected. Is it possible to have this added to the service file? (I'm up for opening a pull request too, let me know)

(Another related open-vm-tools systemd service ```run-vmblock\x2dfuse.mount``` also cannot be confined.)

**Comment by bzed** [comment]
When does appamor.service start?  Open VM tools need to start very early and needs to be able to do things like network configuration before the network starts. 


So please open the bug in the upstream bug tracker. Somebody needs to do qa here.

**Comment by goldstar611** [comment]
The apparmor user mode service (https://gitlab.com/apparmor/apparmor/blob/master/parser/apparmor.service) starts right after the file system is loaded.

Where is the upstream branch? The vmware/open-vm-tools GitHub repo did not have any system related files when I searched.

**Comment by bzed** [comment]
> The apparmor user mode service (https://gitlab.com/apparmor/apparmor/blob/master/parser/apparmor.service) starts right after the file system is loaded.

Just reviewed it on my Debian system - looks fine. Please note that this repository is only used for Debian und derivates :)

> Where is the upstream branch? The vmware/open-vm-tools GitHub repo did not have any system related files when I searched.

hmm, seems they were removed.
