### ISSUE TITLE
Moving vmhgfs-fuse into open-vm-tools

### ISSUE THREAD

**Issue by DanHam** [bzed/pkg-open-vm-tools#4]
Hi,

Firstly, thanks for your work creating these packages for us... it really is much appreciated!

With regard to the request to move vmhgfs-fuse into open-vm-tools (https://bugs.launchpad.net/ubuntu/+source/open-vm-tools/+bug/1551558) please see the comment I made regarding the suggestion below... 

Apologies if this is the wrong place to raise such concerns, but I do think that the including vmhgfs-fuse in open-vm-tools is the wrong way to address the issue. 

--- %< ---

I'm in agreement with the fact that vmhgfs-fuse is part of the wrong package. Having to install a bunch of desktop/X Windows packages just to be able to used shared folders under VMware Workstation/Fusion is certainly less than ideal.

However, I am against including vmhgfs-fuse in the open-vm-tools package as this would mean installing unnecessary binaries within VM guests running on non Workstation/Fusion systems. Clearly there is no need for vmhgfs-fuse within a VM running on top of VMware ESXi as ESXi has no need for, or concept of shared folders.

As such, could we instead break out vmhgfs-fuse (and any additional deps from the open-vm-tools-desktop package) into a completely separate package? This seems to make the most sense to me and would give everyone the ability to install the tools they need without any additional cruft!

Perhaps a name change would be in order as well? To the uninitiated 'vmhgfs-fuse' doesn't really tell you what the package does or give any clue as to its intended use. Perhaps 'open-vm-tools-shared-folders' would be better albeit a little long...

**Comment by bzed** [comment]
Hi,

although I support your statement that moving vmhgfs-fuse into the open-vm-tools package I also do not think that adding yet another binary package is the right way to fix the issue. It would be a rather small package and more or less a waste of space.

Did somebody investigate how many libraries (in terms of disk space) the -desktop package pulls in? I could imagine that this is fully acceptable, even on servers. Also - for servers - I don't think that vmhgfs is somthing one should use, there are better options for (shared) storage...

Thanks for your comments and thoughts!
I'll leave this issue open, maybe there is a better solution we didn't think about yet.

**Comment by DanHam** [comment]
Hi,

Thanks for taking the time to respond. If you feel that moving vmhgfs-fuse into open-vm-tools represents the best possible compromise with regard to use of shared folders then I certainly won't argue further. Perhaps those using open-vm-tools on non Workstation/Fusion systems can just live with the small addition or just blacklist the vmhgfs kernel module to prevent it from being loaded. I certainly believe this is preferable to leaving vmhgfs-fuse in the -desktop package.

I took a quick look at the differences between open-vm-tools and open-vm-tools-desktop. Note this is for CentOS 7 64.

$ yum install open-vm-tools
...
Install  1 Package (+3 Dependent packages)
Total download size: 7.4 M
Installed size: 26 M

$ yum install open-vm-tools-desktop
...
Install  1 Package (+50 Dependent packages)
Total download size: 18 M
Installed size: 64 M

The amount of disk space consumed is clearly minimal; However, the sheer number of extra packages is something I would feel rather upset about having lurking on a server system.

With regard to your comment surrounding use of vmhgfs on servers - I agree; there are certainly better alternatives. However, using shared folders is extremely convenient. Indeed for tools such as [Vagrant](https://www.vagrantup.com/) ([Vagrant on Github](https://github.com/mitchellh/vagrant)) the use of shared folders have become an integral part of the work flow. The fact that the vmhgfs-fuse module is not installed as part of open-vm-tools has been forcing use of the traditional VMware tools to provide the host-guest shared folder functionality (and this has not been without issue). Hopefully, with the move of vmhgfs-fuse into open-vm-tools will now allow people to use open-vm-tools.

Thanks again,

Dan

**Comment by bzed** [comment]
After investigating a bit more: all other vmhgfs tools are in open-vm-tools. But as the module was removed, they would be pretty much useless there. So I've move the vmhgfs-fuse to open-vm-tools.
