### ISSUE TITLE
fuse should be a dependancy for open-vm-tools. 

### ISSUE THREAD

**Issue by DanHam** [bzed/pkg-open-vm-tools#5]
Hi,

I've been using open-vm-tools with Debian 8.5 (Jessie) from the backports repository - version 10.0.7-3227872-4~bpo8+1.

Since vmhgfs-fuse is now included in open-vm-tools the fuse package should be installed as a dependency. Shared folders do not work without the fuse package which currently needs to be installed manually.

Many thanks

Dan

**Comment by bzed** [comment]
hi,

fuse is listed in recommends as it is not wanted by everybody. recommends are installed by default - if not, and you've disabled the installation of recommended packages, you'll have to figure out what you need.

Bernd

**Comment by DanHam** [comment]
hi Bernd,

You're right - I've configured APT to not install recommends as if they were dependencies. I really don't like the fact that 'recommended' packages are installed by default. The choice to make this the default means the whole 'recommends' thing is open to abuse, or at least means that what should be included as a dependency and what should be included as a recommended package is completely ambiguous. On a minimal install, installing recommend packages leads to around 60 additional packages being installed and an image size +250Mb greater than would otherwise have been the case... but I'm getting off topic!!

From the Debian Policy manual:

> Depends
> ...
> The Depends field should be used if the depended-on package is required for the depending package to provide a significant amount of functionality. 
> ...
> Recommends
> This declares a strong, but not absolute, dependency. 

I guess we could get into semantics about what constitutes "significant functionality" or "a strong, but not absolute, dependency"... this is the reason I don't like the whole recommends thing :) However, please note that without fuse, the shared folders feature is _essentially broken_. I guess I'm arguing that since open-vm-tools now supports shared folders that it should do so 'out of the box' i.e. by including fuse as a dependency and not through the _assumed_ installation of a 'recommended' package.

> fuse is listed in recommends as it is not wanted by everybody.

I know I've mentioned this before :)... but perhaps this is good reason to reopen the argument for splitting out shared folder support into it's own separate package? This could be done in much the same way as open-vm-tools-desktop was split out to support integrations specifically for guests with desktops. 

Perhaps open-vm-tools-shared-folders or open-vm-tools-hgfs?

Again, thanks for taking the time to respond.

Dan
