### ISSUE TITLE
Installation of open-vm-tools should automatically create the /mnt/hgfs directory

### ISSUE THREAD

**Issue by DanHam** [bzed/pkg-open-vm-tools#6]
Hi,

I've been using open-vm-tools with Debian 8.5 (Jessie) from the backports repository - version 10.0.7-3227872-4~bpo8+1. 

Without the presence of the /mnt/hgfs directory shared folders cannot be enabled or mounted within the guest. Mounting of the shared folder fails using both the Workstation/Fusion GUI or using the vmrun utility.

`vmrun -T fusion enableSharedFolders /path/to/vmxfile.vmx`
`Error: There was an error mounting the Shared Folders file system inside the guest operating system`

While it is of course easy to create the /mnt/hgfs directory when interacting manually with the guest, tools such as [Vagrant](https://www.vagrantup.com) expect it to be present and will fail to mount shared folders if it is not present. As such it would be great if the directory could be created when open-vm-tools is installed.

Many thanks,

Dan

**Comment by bzed** [comment]
hi,

unfortunately shipping the directory in the package is not possible as it is forbidden by the Debian policy.
I'll figure out / discuss if its possible to create/remove the directory in postinst/prerm.

best regards,
bernd

**Comment by zyv** [comment]
@DanHam it doesn't matter whether the directories in /mnt get created by maintainer scripts or are shipped within the package; in fact, the former is even worse than the later, because it makes it way harder to audit what changes are going to be made by the package to the filesystem.

I would like to suggest to close this as a wontfix and instead use appropriate provisioning mechanisms. I appreciate the user experience concerns, but I see no way to implement this such that it wouldn't infringe on Debian policy.

**Comment by bzed** [comment]
Thanks for your reply, @zyv, appreciated!

**Comment by DanHam** [comment]
@bzed @zyv Thank you for taking the time to look into this. It's a shame this couldn't be done using the postinst/prerm mechanism and I still can't quite understand why Debian policy would be against creating the directory when it is vital for the correct functioning of the package. However, I will of course defer to your expertise with regard to Debian packaging and policy!

I guess the real issue is that there are going to be users (such as myself) who are confused by the fact that shared folders are not working despite having installed the required open-vm-tools package. It would be helpful if the need for the user to manually create the /mnt/hgfs package was clearly iterated somewhere in the package doc files or man pages. This would, by some small meaure, alleviate some of the concerns with user experience that would be certain to occur otherwise.

Thanks once again,

Dan

**Comment by zyv** [comment]
> It's a shame this couldn't be done using the postinst/prerm mechanism and I still can't quite understand why Debian policy would be against creating the directory when it is vital for the correct functioning of the package.

It's not that it can't be done, technically, you can totally do whatever you want from the package maintainer scripts, including `rm -rf /`, the question is what consequences these actions are going to entail... Shipping directories in `/mnt` is disallowed by the policy and causes direct autoreject of such packages for a good reason:

https://lintian.debian.org/tags/dir-or-file-in-mnt.html

Specifically, imagine I mounted something on /mnt and then installed your package shipping stuff in /mnt. Your package has just botched my mounted filesystem (or failed to install, if I mounted it as read-only). Using /mnt as a temporary mount point is a quite common pattern among system administrators, even though it might seem weird to you as a user.

I pondered about it for awhile and ideally VMware tools should just follow FHS and use /media for its shared folders mount points. I do understand, however, that patching this stuff downstream and keeping it up to date is a hell lot of ungrateful work.

Another idea that I came up with as an alternative to creating the directory unconditionally in postinst, which is a no-go (see above), would be a debconf dialog defaulting to "false" in non-interactive mode shown if /mnt/hgfs doesn't exist, explaining that /mnt/hgfs is needed for the correct functioning of the shared folders functionality, and suggesting to create this directory. I asked on -devel, and it seems that it is seen as a reasonable solution...

@bzed ?

**Comment by DanHam** [comment]
@zyv Many thanks for taking the time to explain this to me. While I am an end user I am also a sysadmin. I'm slightly ashamed I didn't foresee the possible issues surrounding creation of the hgfs mountpoint under /mnt. _I sometimes use /mnt as a temp mount point!_ My only excuse is that the VMware Tools installer shipped with VMware Workstation/Fusion creates this directory for you. I have rather naively asked for the same of the open-vm-tools installer.

> I pondered about it for awhile and ideally VMware tools should just follow FHS and use /media for its shared folders mount points.

Agreed. I guess this illustrates why adhering to  FHS is so important.

> I do understand, however, that patching this stuff downstream and keeping it up to date is a hell lot of ungrateful work.

_**I would be grateful!**_ :grin: However, while probably the right choice,  I can see that this fix is unlikely to happen. Given that `/mnt/hgfs` has been used by VMware for rather a long time, I wonder if such a change would cause more issues than it actually solved.

> a debconf dialog defaulting to "false" in non-interactive mode shown if /mnt/hgfs doesn't exist

That is a great suggestion. May I suggest also providing the same info under `/usr/share/doc/open-vm-tools` for those automating their installs with `DEBIAN_FRONTEND="noninteractive"`.

Once again, many thanks to all!

Dan
